name       : caddy
version    : 2.6.4
release    : 13
source     :
    - https://github.com/caddyserver/caddy/archive/refs/tags/v2.6.4.tar.gz : 41f26a7e494eb0e33cd1f167b3f00a4d9030b2f9d29f673a1837dde7bb5e82b0
    - git|https://github.com/caddyserver/dist.git : v2.6.4
license    : Apache-2.0
component  : programming
summary    : Fast, multi-platform web server with automatic HTTPS
description: |
    Caddy is a powerful, open source web server with automatic HTTPS written in Go
networking : yes
builddeps  :
    - golang
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-update-command-functionality.patch
    cp -r $sources/dist* dist
    %patch -p1 < $pkgfiles/tweaked-welcome-site.patch
build      : |
    go build -o caddy cmd/caddy/main.go
install    : |
    install -Dm00755 caddy $installdir/usr/bin/caddy

    install -Dm00644 $pkgfiles/caddy.sysusers $installdir/%libdir%/sysusers.d/caddy.conf
    install -Dm00644 $pkgfiles/caddy.tmpfiles $installdir/%libdir%/tmpfiles.d/caddy.conf

    # Install systemd services and default config
    install -Dm00644 dist/init/caddy.service dist/init/caddy-api.service -t $installdir/%libdir%/systemd/system
    install -Dm00644 $pkgfiles/caddy.preset $installdir/%libdir%/systemd/system-preset/caddy.preset
    install -Dm00644 dist/config/Caddyfile $installdir/usr/share/caddy/Caddyfile

    # Install default welcome page
    install -Dm00644 dist/welcome/index.html $installdir/usr/share/caddy/index.html

    # Generate completions since they were removed from dist
    # without implementing the replacement. See https://github.com/caddyserver/dist/issues/82
    install -dm00755 $installdir/usr/share/bash-completion/completions
    install -dm00755 $installdir/usr/share/zsh/site-functions
    install -dm00755 $installdir/usr/share/fish/vendor_completions.d

    ./caddy completion bash > $installdir/usr/share/bash-completion/completions/caddy
    ./caddy completion zsh > $installdir/usr/share/zsh/site-functions/_caddy
    ./caddy completion fish > $installdir/usr/share/fish/vendor_completions.d/caddy.fish
