name       : caddy
version    : 2.3.0
release    : 1
source     :
    - https://github.com/caddyserver/caddy/archive/v2.3.0.tar.gz : 4688b122ac05be39622aa81324d1635f1642e4a66d731e82d210aef78cf2766a
    - git|https://github.com/caddyserver/dist : 8503149e68db298dbe87253e9fbc9792cbe318f8
    - https://raw.githubusercontent.com/caddyserver/website/4827cff65967435cd3db6b90bc5da6355e868f6a/src/docs/markdown/command-line.md : 09bddfb34256cb1c254f3d232841d2bf6541e004ea7790cdd04b2c397c454f67
license    : Apache-2.0
component  : programming
summary    : Fast, multi-platform web server with automatic HTTPS
description: |
    Caddy is a powerful, open source web server with automatic HTTPS written in Go
networking : yes
builddeps  :
    - golang
setup      : |
    cp -r $sources/dist* dist
build      : |
    go build -o caddy cmd/caddy/main.go
install    : |
    install -Dm00755 caddy $installdir/usr/bin/caddy

    install -Dm00644 $pkgfiles/caddy.sysusers $installdir/%libdir%/sysusers.d/caddy.conf
    install -Dm00644 $pkgfiles/caddy.tmpfiles $installdir/%libdir%/tmpfiles.d/caddy.conf
    install -Dm00644 $pkgfiles/caddy.service dist/init/caddy-api.service -t $installdir/%libdir%/systemd/system
    install -Dm00644 $pkgfiles/Caddyfile $installdir/usr/share/caddy/Caddyfile

    install -Dm00644 dist/welcome/index.html $installdir/usr/share/caddy/index.html
    install -Dm00644 dist/scripts/completions/bash-completion $installdir/usr/share/bash-completion/completions/caddy
    install -Dm00644 dist/scripts/completions/_caddy $installdir/usr/share/zsh/site-functions/_caddy
