name       : caddy
version    : 2.4.5
release    : 5
source     :
    - https://github.com/caddyserver/caddy/archive/refs/tags/v2.4.5.tar.gz : f25a24dfd6398e02ed3e530621f800eb7c7496d302d0a86b6932c219e46320cd
    - git|https://github.com/caddyserver/dist : 2f23e8a67eba98613ba87f2d04768f6b28875386
license    : Apache-2.0
component  : programming
summary    : Fast, multi-platform web server with automatic HTTPS
description: |
    Caddy is a powerful, open source web server with automatic HTTPS written in Go
networking : yes
builddeps  :
    - golang
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-update-command-functionality.patch
    cp -r $sources/dist* dist
build      : |
    go build -o caddy cmd/caddy/main.go
install    : |
    install -Dm00755 caddy $installdir/usr/bin/caddy

    install -Dm00644 $pkgfiles/caddy.sysusers $installdir/%libdir%/sysusers.d/caddy.conf
    install -Dm00644 $pkgfiles/caddy.tmpfiles $installdir/%libdir%/tmpfiles.d/caddy.conf
    install -Dm00644 $pkgfiles/caddy.service dist/init/caddy-api.service -t $installdir/%libdir%/systemd/system
    install -Dm00644 $pkgfiles/Caddyfile $installdir/usr/share/caddy/Caddyfile

    install -Dm00644 dist/welcome/index.html $installdir/usr/share/caddy/index.html
    install -Dm00644 dist/scripts/completions/bash-completion $installdir/usr/share/bash-completion/completions/caddy
    install -Dm00644 dist/scripts/completions/_caddy $installdir/usr/share/zsh/site-functions/_caddy
