name       : caddy
version    : 2.5.0
release    : 8
source     :
    - https://github.com/caddyserver/caddy/archive/refs/tags/v2.5.0.tar.gz : 65b050af067dba4ff28d10dede5973a70474e7a7fc89ad8d7bc353f7c022732f
    - git|https://github.com/caddyserver/dist : 69bb1c539b3ee03fc91271a71653a77ca1e9d131
license    : Apache-2.0
component  : programming
summary    : Fast, multi-platform web server with automatic HTTPS
description: |
    Caddy is a powerful, open source web server with automatic HTTPS written in Go
networking : yes
builddeps  :
    - golang
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-update-command-functionality.patch
    cp -r $sources/dist* dist
build      : |
    go build -o caddy cmd/caddy/main.go
install    : |
    install -Dm00755 caddy $installdir/usr/bin/caddy

    install -Dm00644 $pkgfiles/caddy.sysusers $installdir/%libdir%/sysusers.d/caddy.conf
    install -Dm00644 $pkgfiles/caddy.tmpfiles $installdir/%libdir%/tmpfiles.d/caddy.conf
    install -Dm00644 $pkgfiles/caddy.service dist/init/caddy-api.service -t $installdir/%libdir%/systemd/system
    install -Dm00644 $pkgfiles/Caddyfile $installdir/usr/share/caddy/Caddyfile

    install -Dm00644 dist/welcome/index.html $installdir/usr/share/caddy/index.html
    install -Dm00644 dist/scripts/completions/bash-completion $installdir/usr/share/bash-completion/completions/caddy
    install -Dm00644 dist/scripts/completions/_caddy $installdir/usr/share/zsh/site-functions/_caddy
