name       : caddy
version    : 2.4.2
release    : 3
source     :
    - https://github.com/caddyserver/caddy/archive/refs/tags/v2.4.2.tar.gz : f6319d36f4e27a197c9aa832524a256ca9a9760f8334b52fbb6c618e63b22bf9
    - git|https://github.com/caddyserver/dist : 8eebe8e1ab32cdd210fa7b5b12ff77e696687477
    - https://raw.githubusercontent.com/caddyserver/website/1957b7f536a6aee4666f42ad4ae679ac63001581/src/docs/markdown/command-line.md : 7e603fc6fdc7c0d5a30a88a391fa80e80860927483e4754c034c36733ce1bd1d
license    : Apache-2.0
component  : programming
summary    : Fast, multi-platform web server with automatic HTTPS
description: |
    Caddy is a powerful, open source web server with automatic HTTPS written in Go
networking : yes
builddeps  :
    - golang
setup      : |
    cp -r $sources/dist* dist
build      : |
    go build -o caddy cmd/caddy/main.go
install    : |
    install -Dm00755 caddy $installdir/usr/bin/caddy

    install -Dm00644 $pkgfiles/caddy.sysusers $installdir/%libdir%/sysusers.d/caddy.conf
    install -Dm00644 $pkgfiles/caddy.tmpfiles $installdir/%libdir%/tmpfiles.d/caddy.conf
    install -Dm00644 $pkgfiles/caddy.service dist/init/caddy-api.service -t $installdir/%libdir%/systemd/system
    install -Dm00644 $pkgfiles/Caddyfile $installdir/usr/share/caddy/Caddyfile

    install -Dm00644 dist/welcome/index.html $installdir/usr/share/caddy/index.html
    install -Dm00644 dist/scripts/completions/bash-completion $installdir/usr/share/bash-completion/completions/caddy
    install -Dm00644 dist/scripts/completions/_caddy $installdir/usr/share/zsh/site-functions/_caddy
